### PR TITLE
Added single file extraction to QAR

### PR DESCRIPTION
**Pull request by topher-au**

### CODE REVIEW

**Comment by Atvaark** [comment]
Hey topher,

when would you want to just export a single file from a .dat archive via the command line? The resulting .xml file would not be very useful, as you can't repack the .dat file properly.

Apart from that these are some issues in your changes:
- The new command line argument is checked in the class library assembly GzsTool.Core. This will break other applications that use GzsTool.Core and use different command line arguments. I'd rather parse the command line argument in the console application assembly GzsTool and use a different _Export_-method. (e.g. _bool TryExport(ulong hash, out Stream stream)_)
- _ExportFiles_ modifies the _Entries_ list if a 2nd command line argument is set. This will break subsequent calls of the method. Since the method returns a lazy evalulated IEnumerable<T>, just use LINQ to filter the files you don't want to export. (That would just require a _public ulong Hash_-property in the FileDataStreamContainer class.)

I'd say that you should just reference GzsTool.Core instead of adding that command line argument.

**Comment by topher-au** [comment]
Please disregard that entirely, drunken coding is never a good idea :p I
have come up with a much better way of doing what I need to haha.

Hey topher,

when would you want to just export a single file from a .dat archive via
the command line? The resulting .xml file would not be very useful, as you
can't repack the .dat file properly.

Apart from that these are some issues in your changes:
- The new command line argument is checked in the class library assembly
  GzsTool.Core. This will break other applications that use GzsTool.Core and
  use different command line arguments. I'd rather parse the command line
  argument in the console application assembly GzsTool and use a different
  _Export_-method. (e.g. _bool TryExport(ulong hash, out Stream stream)_)
- _ExportFiles_ modifies the _Entries_ list if a 2nd command line
  argument is set. This will break subsequent calls of the method. Since the
  method returns a lazy evalulated IEnumerable, just use LINQ to filter the
  files you don't want to export. (That would just require a _public ulong
  Hash_-property in the FileDataStreamContainer class.)

I'd say that you should just reference GzsTool.Core instead of adding that
command line argument.

**Comment by Atvaark** [comment]
Don't sweat it. Did you find a solution that doesn't require a custom GzsTool?

**Comment by topher-au** [comment]
Yeah, SnakeBite is my first real C# application and I'm 100% self-taught so
I'm still learning things like crazy. I've actually written some wrapper
functions for GzsTool.Core that allow me to perform the functions I need
without calling the app from the command line. About 1000x more robust and
efficient!

On Tue, Oct 20, 2015 at 8:58 PM, Atvaark notifications@github.com wrote:

> Don't sweat it. Did you find a solution that doesn't require a custom
> GzsTool?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Atvaark/GzsTool/pull/1#issuecomment-149502691.

## 

Thankyou,
Chris Sheridan lordramza@gmail.com

**Comment by Atvaark** [comment]
Nice to hear that you're so ambitious with your first C# project. If you have any other ideas for changes don't be afraid of opening a new issue.

**Comment by topher-au** [comment]
Thanks. I actually wrote a function for converting a filename to its' hash
because I was ending up with the hash filenames being re-hashed sometimes,
maybe you'd find something like that useful in GzsTool.

**Pull request closed without merging**
